### PR TITLE
All 4 Issues Fixes

### PR DESCRIPTION
**Pull request by yashkapoor8710**

### CODE REVIEW

**Comment by manojsinghnegiwd** [comment]
@yashkapoor8710 Please add screenshots is there are any UI changes

**Comment by yashkapoor8710** [comment]
Screenshot 2020-04-01 at 10 19 27 AM

**Comment by yashkapoor8710** [comment]
Screenshot 2020-04-01 at 10 19 55 AM

**Comment by yashkapoor8710** [comment]
Screenshot 2020-04-01 at 10 20 31 AM

**Comment by yashkapoor8710** [comment]
Screenshot 2020-04-01 at 10 21 22 AM

**Comment by yashkapoor8710** [comment]
Screenshot 2020-04-01 at 10 32 43 AM

**Pull request merged**
